**Panda Function1**

In [2]:
import pandas as pd
csv_1= pd.read_csv("F:\\panda_jupyter\\employees.csv")
csv_1

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,7-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,3-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,5-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,7-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,7-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,7-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30

In [3]:
csv_1.index

RangeIndex(start=0, stop=25, step=1)

In [4]:
csv_1.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [5]:
csv_1.describe()

       EMPLOYEE_ID        SALARY  DEPARTMENT_ID
count    25.000000     25.000000       25.00000
mean    141.520000   8716.640000       68.40000
std      46.475011   5079.447172       31.44837
min     100.000000   2600.000000       10.00000
25%     106.000000   4800.000000       50.00000
50%     112.000000   7800.000000       60.00000
75%     200.000000  11000.000000      100.00000
max     206.000000  24000.000000      110.00000

In [6]:
csv_1.head() #it show top 5 rows

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20

In [7]:
csv_1.tail(2) # it show 2 row from down we pass arrgument 2

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30

In [8]:
csv_1[6:11] #accessing other rows with slicing

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
6,204,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90

In [9]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [10]:
#csv_1.index.array # converting into array

In [11]:
#csv_1.to_numpy() # converting into numpy array

In [12]:
import numpy as np  #converting into numpy array
v =np.array(csv_1)
v

array([[198, 'Donald', 'OConnell', 'DOCONNEL', '650.507.9833',
        '21-Jun-07', 'SH_CLERK', 2600, ' - ', '124', 50],
       [199, 'Douglas', 'Grant', 'DGRANT', '650.507.9844', '13-Jan-08',
        'SH_CLERK', 2600, ' - ', '124', 50],
       [200, 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444',
        '17-Sep-03', 'AD_ASST', 4400, ' - ', '101', 10],
       [201, 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555',
        '17-Feb-04', 'MK_MAN', 13000, ' - ', '100', 20],
       [202, 'Pat', 'Fay', 'PFAY', '603.123.6666', '17-Aug-05', 'MK_REP',
        6000, ' - ', '201', 20],
       [203, 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', '7-Jun-02',
        'HR_REP', 6500, ' - ', '101', 40],
       [204, 'Hermann', 'Baer', 'HBAER', '515.123.8888', '7-Jun-02',
        'PR_REP', 10000, ' - ', '101', 70],
       [205, 'Shelley', 'Higgins', 'SHIGGINS', '515.123.8080',
        '7-Jun-02', 'AC_MGR', 12008, ' - ', '101', 110],
       [206, 'William', 'Gietz', 'WGIETZ', '515.123.8181', '7-Jun-02',
        'AC_ACCOUNT', 8300, ' - ', '205', 110],
       [100, 'Steven', 'King', 'SKING', '515.123.4567', '17-Jun-03',
        'AD_PRES', 24000, ' - ', ' - ', 90],
       [101, 'Neena', 'Kochhar', 'NKOCHHAR', '515.123.4568', '21-Sep-05',
        'AD_VP', 17000, ' - ', '100', 90],
       [102, 'Lex', 'De Haan', 'LDEHAAN', '515.123.4569', '13-Jan-01',
        'AD_VP', 17000, ' - ', '100', 90],
       [103, 'Alexander', 'Hunold', 'AHUNOLD', '590.423.4567',
        '3-Jan-06', 'IT_PROG', 9000, ' - ', '102', 60],
       [104, 'Bruce', 'Ernst', 'BERNST', '590.423.4568', '21-May-07',
        'IT_PROG', 6000, ' - ', '103', 60],
       [105, 'David', 'Austin', 'DAUSTIN', '590.423.4569', '25-Jun-05',
        'IT_PROG', 4800, ' - ', '103', 60],
       [106, 'Valli', 'Pataballa', 'VPATABAL', '590.423.4560',
        '5-Feb-06', 'IT_PROG', 4800, ' - ', '103', 60],
       [107, 'Diana', 'Lorentz', 'DLORENTZ', '590.423.5567', '7-Feb-07',
        'IT_PROG', 4200, ' - ', '103', 60],
       [108, 'Nancy', 'Greenberg', 'NGREENBE', '515.124.4569',
        '17-Aug-02', 'FI_MGR', 12008, ' - ', '101', 100],
       [109, 'Daniel', 'Faviet', 'DFAVIET', '515.124.4169', '16-Aug-02',
        'FI_ACCOUNT', 9000, ' - ', '108', 100],
       [110, 'John', 'Chen', 'JCHEN', '515.124.4269', '28-Sep-05',
        'FI_ACCOUNT', 8200, ' - ', '108', 100],
       [111, 'Ismael', 'Sciarra', 'ISCIARRA', '515.124.4369',
        '30-Sep-05', 'FI_ACCOUNT', 7700, ' - ', '108', 100],
       [112, 'Jose Manuel', 'Urman', 'JMURMAN', '515.124.4469',
        '7-Mar-06', 'FI_ACCOUNT', 7800, ' - ', '108', 100],
       [113, 'Luis', 'Popp', 'LPOPP', '515.124.4567', '7-Dec-07',
        'FI_ACCOUNT', 6900, ' - ', '108', 100],
       [114, 'Den', 'Raphaely', 'DRAPHEAL', '515.127.4561', '7-Dec-02',
        'PU_MAN', 11000, ' - ', '100', 30],
       [115, 'Alexander', 'Khoo', 'AKHOO', '515.127.4562', '18-May-03',
        'PU_CLERK', 3100, ' - ', '114', 30]], dtype=object)

In [13]:
csv_1.sort_index(axis=0,ascending=False) #sort in descending order

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000,-,100,30
22,113,Luis,Popp,LPOPP,515.124.4567,7-Dec-07,FI_ACCOUNT,6900,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,7-Mar-06,FI_ACCOUNT,7800,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,7-Feb-07,IT_PROG,4200,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,5-Feb-06,IT_PROG,4800,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,3-Jan-06,IT_PROG,9000,-,102,60
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
8,206,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300,-,205,110
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008,-,101,110
6,204,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,10000,-,101,70
5,203,Susan,Mavris,SMAVRIS,515.123.7777,7-Jun-02,HR_REP,6500,-,101,40
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50

In [17]:
csv_1["EMPLOYEE_ID"][0]="PYTHON"
csv_1

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,PYTHON,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,7-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,3-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,5-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,7-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,7-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,7-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30

In [19]:
csv_1.loc[0,"EMPLOYEE_ID"]="COMPANY"
csv_1

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,COMPANY,Donald,OConnell,DOCONNEL,650.507.9833,21-Jun-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-Jan-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-Aug-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,7-Jun-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,7-Jun-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,7-Jun-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,7-Jun-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-Jun-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-Sep-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-Jan-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,3-Jan-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-May-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-Jun-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,5-Feb-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,7-Feb-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-Aug-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-Aug-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-Sep-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-Sep-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,7-Mar-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,7-Dec-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,7-Dec-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-May-03,PU_CLERK,3100,-,114,30

In [23]:
csv_1.loc[[2,3],["EMPLOYEE_ID","FIRST_NAME"]] #To get a particuler data

  EMPLOYEE_ID FIRST_NAME
2         200   Jennifer
3         201    Michael

In [26]:
# csv_1.loc[:,["EMPLOYEE_ID","FIRST_NAME"]]

In [27]:
csv_1.loc[[2,3],:]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-Sep-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-Feb-04,MK_MAN,13000,-,100,20

In [29]:
csv_1.iloc[0,4] #iloc is another method to get particular value [row _index,column_index]

'650.507.9833'

In [32]:
# csv_1.drop("DEPARTMENT_ID",axis=1) #drop the column or row

In [34]:
#csv_1.drop(0,axis=0)